#!/bin/bash

if [ -z "$1" ]; then
    exit 1
fi

#Handle install, URL_FILE, and test commands
case "$1" in
    install)
        npm install
        # Installation commands TBD
        ;;
    test)
        echo "Running tests..."
        # Test commands TBD
        ;;
    *)
        link_regex="^https?:\/\/.*$"
        if [[ $1 =~ $link_regex ]]; then
            echo "Parsing with Typescript"
            npx ts-node ./src/process_url.ts $1
        else
            echo "Invalid URL"
            exit 1
        fi
        ;;
esac