#!/bin/bash

if [ -z "$1" ]; then
    exit 1
fi

#Handle install, URL_FILE, and test commands
case "$1" in
    install)
        echo "Running installation..."
        # Installation commands TBD
        ;;
    test)
        echo "Running tests..."
        # Test commands TBD
        ;;
    *)
        echo "regexing url"
        npm_regex="^https:\/\/www\.npmjs\.com\/package\/.*$"
        github_regex="^https:\/\/github\.com\/.*$"
        if [[ $1 =~ $npm_regex ]]; then
            echo "npm"
            npx ts-node process_npm.ts $1
        elif [[ $1 =~ $github_regex ]]; then
            echo "github"
            npx ts-node process_npm.ts $1
        else
            echo "Invalid URL"
            exit 1
        fi
        ;;
esac