#!/bin/bash

if [ -z "$1" ]; then
    echo "no command entered"
    exit 1
fi

#Handle install, URL_FILE, and test commands
case "$1" in
    install)
        npm install
        if [ $? -eq 0 ]; then
            echo "Dependencies installed successfully."
        else
            echo "Failed to install dependencies."
            exit 1
        fi
        # Installation commands TBD
        ;;
    # test)
    #     echo "Running tests..."
    #     # Test commands TBD
    #     ;;
    *)
        npx ts-node ./src/process_url.ts "$@"
    ;;
esac
